/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const QuoteRequest = IDL.Record({
  'status' : IDL.Text,
  'videoLength' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'created_at' : Time,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'checkAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'deleteQuote' : IDL.Func([Time], [], []),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'submitQuote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateQuoteStatus' : IDL.Func([Time, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const QuoteRequest = IDL.Record({
    'status' : IDL.Text,
    'videoLength' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : Time,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'checkAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'deleteQuote' : IDL.Func([Time], [], []),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'submitQuote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateQuoteStatus' : IDL.Func([Time, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };